services:
  app:
    build: .
    ports:
      - "8000:8000"

    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

volumes:
  postgres_data:
