# Generated by Django 5.1.3 on 2024-11-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
    ]
