# Generated by Django 5.1.3 on 2024-11-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_user_last_login_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
