# Generated by Django 5.1.3 on 2024-11-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_ipaddress"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IPAddress",
        ),
    ]
